version: "2"

run:
  timeout: 5m

linters:
  enable:
    - revive
    - goconst
    - gocritic
    - gocyclo
    - misspell
    - lll
    - unparam
    - prealloc
    - testifylint

  settings:
    lll:
      line-length: 120
    gocyclo:
      min-complexity: 15

